### ISSUE TITLE
Error in mc/skins/zenburn.ini at line 121

### ISSUE THREAD

**Issue by trefmanic** [troydm/dotfiles#1]
Current line:  menusel=color108;**color**color234
Should be:     menusel=color108;color234

Looks like a typo.

**Comment by troydm** [comment]
yeah, seems so, also this repo is outdated and for historical reasons only, will remove it probably soon, grab latest version from here

https://github.com/troydm/dotcentral/blob/master/configurations/common/mc/skins/zenburn.ini
